# Generated by Django 5.2.1 on 2025-07-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('ntcno', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('ntitle', models.CharField(max_length=1000)),
                ('ncontent', models.TextField()),
                ('nfile', models.ImageField(blank=True, null=True, upload_to='notice')),
                ('nhit', models.IntegerField(default=0)),
                ('ndate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inqno', models.AutoField(primary_key=True, serialize=False)),
                ('ictgr', models.CharField(max_length=100)),
                ('ititle', models.CharField(max_length=1000)),
                ('icontent', models.TextField()),
                ('ifile1', models.ImageField(blank=True, null=True, upload_to='inquiry')),
                ('ifile2', models.ImageField(blank=True, null=True, upload_to='inquiry')),
                ('ifile3', models.ImageField(blank=True, null=True, upload_to='inquiry')),
                ('idate', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
