# Generated by Django 5.2.1 on 2025-07-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainbanner',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('mtitle', models.CharField(max_length=100)),
                ('mtitle2', models.CharField(max_length=100)),
                ('msubtitle', models.CharField(max_length=100)),
                ('msubtitle2', models.CharField(max_length=100)),
                ('mimg', models.ImageField(upload_to='mainBanner')),
                ('primary', models.IntegerField(default=0)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('murl', models.CharField(default='#', max_length=1000)),
            ],
        ),
    ]
