# Generated by Django 5.2.1 on 2025-07-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booksearch', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('max_member', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('is_public', models.CharField(choices=[('0', '공개'), ('1', '비공개')], default='0', max_length=1)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reading_groups', to='member.member')),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booksearch.book')),
                ('member', models.ManyToManyField(blank=True, related_name='member_reading_groups', to='member.member')),
            ],
        ),
    ]
