# Generated by Django 5.2.1 on 2025-07-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('shareMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
                ('created_at', models.DateField(auto_now_add=True, help_text='작성일')),
                ('likes', models.IntegerField(default=0, help_text='좋아요 수')),
                ('comments', models.IntegerField(default=0, help_text='댓글 수')),
                ('file', models.ImageField(blank=True, help_text='이미지', null=True, upload_to='chat_files/')),
                ('group_id', models.ForeignKey(help_text='그룹 번호', on_delete=django.db.models.deletion.CASCADE, to='shareMain.readinggroup')),
                ('member_id', models.ForeignKey(help_text='회원 번호', on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('parent', models.ForeignKey(blank=True, help_text='부모 메시지 ID (대댓글용)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatrooms.chatmessage')),
            ],
        ),
    ]
